dist: xenial
language: python

env:
  - PYTHON=3.5 BACKEND=agg
  - PYTHON=3.6 BACKEND=agg
  - PYTHON=3.7 BACKEND=agg
  - PYTHON=3.8 BACKEND=agg


before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a


install:
  - conda update conda --yes
  - conda config --add channels conda-forge
  - if [ "$PYTHON" = "3.8" ]; then conda create -n testenv --yes --channel conda-forge/label/pre-3.8 pip python=$PYTHON; else conda create -n testenv --yes pip python=$PYTHON matplotlib; fi
  - source activate testenv
  - pip install .[dev]


script: pytest dabest
